version: "3.8"

services:
  nginx:
    image: library/nginx:1.19.7-alpine
    ports:
    - "80:80"
    environment:
      NGINX_PORT: 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./content-tool/frontend/build:/var/www/html
    depends_on:
      - yama-backend
    #  - yama-content-tool
      - keycloak

  #yama-content-tool:
  #  build: ./content-tool

  yama-backend:
    build: ./backend
    volumes:
    - ./frontend:/app/public
    depends_on:
      - yama-postgres
      - keycloak

  yama-postgres:
    image: postgres
    volumes:
      - ./pg_data-yama:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: yama
      POSTGRES_DB: yama


  keycloak:
    image: quay.io/keycloak/keycloak:12.0.3
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: testadmin
      KEYCLOAK_FRONTEND_URL: http://localhost/auth
    ports:
      - "3000:8080"
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres
    volumes:
      - ./pg_data-keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak